### ISSUE TITLE
The beacon status update does not work

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.beacon.admin.android#33]
Does the trusted user API call really update the status of a nearby beacon?

- [x] See if the trusted update POST to the API works correctly
- [x] See if the admin app can update states of beacons (via trusted user interactions)
- [x] See if the other apps can update the state of beacons (see issues of the Südtirol Guide App)
  > We should open issues within the dedicated repositories
- [x] Update configurations with the admin app on testing 
- [x] ...and production environments 

**DEPRECATED INVALIDATED LIST**

- [x] Create a test environment with only test beacons in it 
  - [x] remove all production beacons from the test DB
  - [x] use the testing kontakt.io account on the test environment
  - [x] use the single (prod+test) trusted user, which is always the same since we have only one app

> Not done, but replaced by https://github.com/noi-techpark/it.bz.beacon.api/issues/57

**Comment by sseppi** [comment]
I tested this funcionality with some beacon and the functionality seems not work.

For example today I interacted with BS30550 and BS30549, but their status is still "NO SIGNAL"

**Comment by bertolla** [comment]
@sseppi 
What functionality are we talking about??? If you are talking about battery status i found the problem. The password contained an '&' and injection the password in the xml file caused it to parse it as &amp; to keep the xml structure valid. When apps are reading this xml file they are probably not unescaping it correctly and therefore use the wrong password.
I manually tried to update the battery status through the API and it worked without problems.
I changed the trusted password and it will work again on follow up releases.
If there is more about this issue please try to explain it thoroughly, since I couldn't determine what the problem exactly was and if there is something more in the deep to fix.

**Comment by sseppi** [comment]
@bertolla 
I've installed the version 0.3.1 on my phone and from the web interface it seems that the battery status isn't still updating.
I see that the field last seen has been correctly updated to 27th of August 2020 but the device status is still "No signal".

Can you please check directly in the DB if the battery status of the following beacons has been updated this morning:
- NOI0141#k3Xf2l
- NOI0142#nzg8gE
- NOI0143#77Z8SX
- NOI0144#c4kxLe

**Comment by rcavaliere** [comment]
All these issues are part of the aspects to be fixed with Davide Montesin and Konverto

**Comment by sseppi** [comment]
This issue will be moved in the backlog and reopened when the new contract will be started

**Comment by sseppi** [comment]
It seems that the call for updating the battery status il already implemented but never called.
